<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "role".
 *
 * @property int $id
 * @property string $ten_role
 *
 * @property User[] $users
 */
class Role extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'role';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'ten_role'], 'required'],
            [['id'], 'integer'],
            [['ten_role'], 'string', 'max' => 20],
            [['id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ten_role' => 'Tên chức vụ',
        ];
    }

    /**
     * Gets query for [[Users]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::class, ['ma_role' => 'id']);
    }

    public function beforeDelete()
    {
        if ($this->getRelatedRecords()){
            throw new \yii\db\IntegrityException('Cannot delete this record due to existing relationships.');
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
